export default [
  {
        ligature: 'va_channel_web',
        css_class: 'va-icon_channel_web',
        unicode: '&#xe901;',
        description: 'channel_web',
  },
  {
        ligature: 'va_channel_tv',
        css_class: 'va-icon_channel_tv',
        unicode: '&#xe902;',
        description: 'channel_tv',
  },
  {
        ligature: 'va_channel_direct',
        css_class: 'va-icon_channel_direct',
        unicode: '&#xe903;',
        description: 'channel_direct',
  },
  {
        ligature: 'va_channel_dooh',
        css_class: 'va-icon_channel_dooh',
        unicode: '&#xe904;',
        description: 'channel_dooh',
  },
  {
        ligature: 'va_channel_audio',
        css_class: 'va-icon_channel_audio',
        unicode: '&#xe905;',
        description: 'channel_audio',
  },
  {
        ligature: 'va_format_video_web',
        css_class: 'va-icon_format_video_web',
        unicode: '&#xe900;',
        description: 'format_video_web',
  },
  {
        ligature: 'va_format_video_app',
        css_class: 'va-icon_format_video_app',
        unicode: '&#xe906;',
        description: 'format_video_app',
  },
  {
        ligature: 'va_format_video_ott',
        css_class: 'va-icon_format_video_ott',
        unicode: '&#xe907;',
        description: 'format_video_ott',
  },
  {
        ligature: 'va_format_ott_smarttv',
        css_class: 'va-icon_format_ott_smarttv',
        unicode: '&#xe908;',
        description: 'format_ott_smarttv',
  },
  {
        ligature: 'va_format_ott_connected_devices',
        css_class: 'va-icon_format_ott_connected_devices',
        unicode: '&#xe909;',
        description: 'format_ott_connected_devices',
  },
  {
        ligature: 'va_format_ott_gaming_consoles',
        css_class: 'va-icon_format_ott_gaming_consoles',
        unicode: '&#xe90a;',
        description: 'format_ott_gaming_consoles',
  },
  {
        ligature: 'va_device_desktop',
        css_class: 'va-icon_device_desktop',
        unicode: '&#xe90b;',
        description: 'device_desktop',
  },
  {
        ligature: 'va_device_mobile',
        css_class: 'va-icon_device_mobile',
        unicode: '&#xe90c;',
        description: 'device_mobile',
  },
  {
        ligature: 'va_device_tablet',
        css_class: 'va-icon_device_tablet',
        unicode: '&#xe90d;',
        description: 'device_tablet',
  },
  {
        ligature: 'va_device_tv',
        css_class: 'va-icon_device_tv',
        unicode: '&#xe90e;',
        description: 'device_tv',
  },
  {
        ligature: 'va_finish',
        css_class: 'va-icon_finish',
        unicode: '&#xe90f;',
        description: 'finish',
  },
  {
        ligature: 'va_completed',
        css_class: 'va-icon_completed',
        unicode: '&#xe910;',
        description: 'completed',
  },
]